SELECT a.nm_piloto, b.nm_equipe
FROM tb_piloto AS a
LEFT JOIN tb_equipe AS b
ON a.id_equipe = b.id_equipe
ORDER BY nm_equipe;

SELECT nm_piloto, dt_nascimento
FROM tb_piloto
ORDER BY dt_nascimento ASC;

SELECT PIT.NM_PILOTO AS "NOME DO PILOTO" , 
       PAS.NM_PAIS "PAÍS DE NASCIMENTO",
       EQP.NM_EQUIPE "NOME DA EQUIPE" ,
       PAS2.NM_PAIS "PAÍS DA EQUIPE",
       RES.NR_COLOCACAO_FINAL "COLOCAÇÃO FINAL", 
       CIT.NM_CIRCUITO "NOME DO CIRCUITO", 
       PRO.DT_PROVA "DATA DA PROVA"
FROM TB_PILOTO as PIT, TB_PAIS as PAS,
	 TB_EQUIPE as EQP, TB_PAIS as PAS2,
	 TB_CIRCUITO as CIT, TB_PROVA as PRO,
	 TB_RESULTADO as RES
 WHERE PAS.ID_PAIS   = PIT.ID_PAIS
   AND EQP.ID_EQUIPE  = PIT.ID_EQUIPE
   AND PAS2.ID_PAIS  = EQP.ID_PAIS
   AND CIT.ID_CIRCUITO = 404
   AND PRO.ID_CIRCUITO = CIT.ID_CIRCUITO
   AND RES.ID_PROVA  = PRO.ID_PROVA
   AND RES.ID_PILOTO = PIT.ID_PILOTO
 ORDER BY RES.NR_COLOCACAO_FINAL;
 

 

